### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by SynedraAcus** [jonathanabennett/Qaf#12]
The game crashes during curses initialization. The system is Linux Mint 17, and I have curses 2.2. Game is launched from xterm. Traceback is as follows:

```
Traceback (most recent call last):
  File "game.py", line 212, in <module>
    curses.wrapper(loop) #Should I put the main loop outside the Game Object?
  File "/usr/lib/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "game.py", line 209, in loop
    g = Game(screen)
  File "game.py", line 19, in __init__
    self.colorize()
  File "game.py", line 85, in colorize
    curses.init_pair(1, 191, -1)
_curses.error: init_pair() returned ERR

```

**Comment by jonathanabennett** [comment]
Can you tell me what OS you are running?

**Comment by SynedraAcus** [comment]
Linux Mint 17 (a fork of Ubuntu) with Cinnamon DE. I have Python3.4, not 3.5, maybe that helps.
```
morozov@morozov-300V3A-300V4A-300V5A ~ $ uname -a
Linux morozov-300V3A-300V4A-300V5A 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alchzh** [comment]
I'm not completely sure but I think this is being caused by trying to move the cursor off the screen of the terminal, or your terminal is not 256-color or something. It doesn't have to do with the python version

EDIT: looks like your error is because it''s not 256 color

@jonathanabennett do we really need the full 256 colors? That will break compat with some terminals

**Comment by acz13** [comment]
curses.init_pair(1, 191, -1) < the 191 is the problem... I think?

**Comment by alchzh** [comment]
@SynedraAcus If you are using a term that supports 256 colors (aka. all of them pretty much) try: `export TERM=xterm-256color`

**Comment by SynedraAcus** [comment]
@acz13 Yes, that's it.

**Comment by jonathanabennett** [comment]
I suppose it doesn't need 256 colors yet, but I do like those colors better and I plan to expand the beastiary. Does anybody know how programs like DCSS (crawl) enforce 256 colors?

**Comment by jonathanabennett** [comment]
I'm preparing the 0.1.1-Alpha release today. I will change the colors so that it doesn't require 256 colors for now. and see how far I can go before I run out of colors.

**Comment by jonathanabennett** [comment]
I'm closing this as resolved in the next release. The resolution was simply to drop all the colors down into the 0-7 range. I wish there was a better option, though. I'll keep looking around.
