### ISSUE TITLE
Optimize screen drawing

### ISSUE THREAD

**Issue by alchzh** [jonathanabennett/Qaf#15]
Currently on every turn when the screen is drawn you're refreshing the whole screen, I think?

Causes some extreme screen flickering for me

**Comment by jonathanabennett** [comment]
I am. I believe that's a limitation of the Python curses library. My understanding is that you have to mark the whole window dirty, you can't just mark sections of it. I'll research it more.

**Comment by jonathanabennett** [comment]
@acz13, I've just pushed a patch into the master that, based on my reading of the python docs might fix this. I never had the issue, so I can't tell if it's made a difference. Can you try it and let me know if there's any improvement?
